-- :::::::::::::::::::::::::: 축제테이블 ::::::::::::::::::::::::::::::::

DROP TABLE FESTIVAL;
DROP SEQUENCE FESTIVALSEQ;

-- 축제번호, 축제명, 내용, 시작날짜, 종료날짜,
-- 장소, 티켓여부(Y/N), 티켓가격, 이미지주소
CREATE SEQUENCE FESTIVALSEQ;

CREATE TABLE FESTIVAL(
	FESTIVAL_NUM NUMBER PRIMARY KEY,
	FESTIVAL_NAME VARCHAR2(2000) NOT NULL,
	FESTIVAL_LOCATION VARCHAR2(4000) NOT NULL,
	FESTIVAL_START VARCHAR2(1000) NOT NULL,
	FESTIVAL_END VARCHAR2(1000) NOT NULL,
	FESTIVAL_CONTENT VARCHAR2(4000) NOT NULL,
	FESTIVAL_ADDRESS VARCHAR2(1000) NOT NULL,
	FESTIVAL_TICKET VARCHAR2(50) NOT NULL,
	FESTIVAL_PRICE NUMBER NOT NULL,	
	FESTIVAL_IMGSRC VARCHAR2(4000)
);

DROP TABLE FESTIVAL

SELECT * FROM FESTIVAL;
DELETE FROM FESTIVAL

SELECT * FROM FESTIVAL 
WHERE FESTIVAL_TICKET IN 'Y'
AND FESTIVAL_IMGSRC NOT IN 'undefined'



-- :::::::::::::::::::::::::: 예매내역 ::::::::::::::::::::::::::::::::
-- 회원아이디, 축베전호, 예매번호, 티켓수량, 총가격, 
-- 결제상태, 취소가능여부
DROP TABLE RESERVATION;

CREATE TABLE RESERVATION(
	MEMBER_ID VARCHAR2(500) NOT NULL,
	FESTIVAL_NUM NUMBER NOT NULL,
	RESERVATION_NUM NUMBER PRIMARY KEY,
	RESERVATION_QUANTITY NUMBER NOT NULL,
	RESERVATION_TOTALPRICE NUMBER NOT NULL,
	RESERVATION_STATUS VARCHAR2(50),
	RESERVATION_CANCLEABLE VARCHAR2(2),
	CONSTRAINT CHK_CANCLEABLE CHECK (RESERVATION_CANCLEABLE IN ('Y', 'N'))
);

-- :::::::::::::::::::::::::: 관심상품 ::::::::::::::::::::::::::::::::
-- 회원아이디, 축제번호
DROP TABLE INTEREST;

CREATE TABLE INTEREST(
	MEMBER_ID VARCHAR2(500),
	FESTIVAL_NUM NUMBER
);


SELECT * FROM FESTIVAL
		WHERE FESTIVAL_START > TO_CHAR(SYSDATE,'YYYY-MM-DD')


