DROP TABLE RESERVATION;
DROP SEQUENCE RESERVATIONSEQ;


-- 회원아이디, 축제번호, 예매번호, 티켓수량, 총가격
-- 현재상태, 취소가능여부
CREATE TABLE RESERVATION(
RESERVATION_NUM NUMBER NOT NULL,
RESERVATION_ID VARCHAR2(1000) NOT NULL,
RESERVATION_F_NUM NUMBER NOT NULL,
RESERVATION_QUANTITY NUMBER NOT NULL,
RESERVATION_TOTALPRICE NUMBER NOT NULL,
RESERVATION_DATE VARCHAR2(500) NOT NULL,
RESERVATION_STATUS VARCHAR2(500) NOT NULL,
RESERVATION_CANCLEABLE VARCHAR2(500) NOT NULL
);

CREATE SEQUENCE RESERVATIONSEQ;

SELECT * FROM RESERVATION WHERE RESERVATION_ID = 'aa';

INSERT INTO RESERVATION
VALUES(RESERVATIONSEQ.NEXTVAL, 'aa', 137, 2, 19900, SYSDATE, '예약완료', 'N')


		SELECT * FROM RESERVATION
		JOIN FESTIVAL 
		ON FESTIVAL_NUM = RESERVATION_F_NUM
		WHERE RESERVATION_ID = 'aa'